// Generated by Supabase (`gen types typescript`). Do not edit by hand.
// Regenerate after any schema change: it reflects public.* tables + functions.
// Last regenerated 2026-08-04 for Phase 2 (menus, memberships, menu_schedules,
// invites, qr_codes, qr_scans, subscriptions, imports, domain_verifications + venue/menu cols).
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          after: Json | null
          before: Json | null
          created_at: string
          entity: string
          entity_id: string | null
          id: number
          tenant_id: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity: string
          entity_id?: string | null
          id?: never
          tenant_id?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity?: string
          entity_id?: string | null
          id?: never
          tenant_id?: string | null
        }
        Relationships: []
      }
      categories: {
        Row: {
          available_from: string | null
          available_to: string | null
          created_at: string
          deleted_at: string | null
          description: string | null
          group_id: string | null
          id: string
          image_url: string | null
          is_active: boolean
          name: string
          name_zh: string | null
          restaurant_id: string
          slug: string
          sort_order: number
          tenant_id: string
          updated_at: string
        }
        Insert: {
          available_from?: string | null
          available_to?: string | null
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          group_id?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          name: string
          name_zh?: string | null
          restaurant_id: string
          slug: string
          sort_order?: number
          tenant_id: string
          updated_at?: string
        }
        Update: {
          available_from?: string | null
          available_to?: string | null
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          group_id?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          name?: string
          name_zh?: string | null
          restaurant_id?: string
          slug?: string
          sort_order?: number
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "menu_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "categories_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "categories_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      domain_verifications: {
        Row: {
          created_at: string
          domain: string
          id: string
          restaurant_id: string
          tenant_id: string
          token: string
          verified_at: string | null
        }
        Insert: {
          created_at?: string
          domain: string
          id?: string
          restaurant_id: string
          tenant_id: string
          token: string
          verified_at?: string | null
        }
        Update: {
          created_at?: string
          domain?: string
          id?: string
          restaurant_id?: string
          tenant_id?: string
          token?: string
          verified_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "domain_verifications_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "domain_verifications_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      imports: {
        Row: {
          accuracy_score: number | null
          created_at: string
          file_url: string | null
          id: string
          restaurant_id: string | null
          result: Json | null
          source: string | null
          status: string | null
          tenant_id: string
        }
        Insert: {
          accuracy_score?: number | null
          created_at?: string
          file_url?: string | null
          id?: string
          restaurant_id?: string | null
          result?: Json | null
          source?: string | null
          status?: string | null
          tenant_id: string
        }
        Update: {
          accuracy_score?: number | null
          created_at?: string
          file_url?: string | null
          id?: string
          restaurant_id?: string | null
          result?: Json | null
          source?: string | null
          status?: string | null
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "imports_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "imports_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      invites: {
        Row: {
          accepted_at: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string | null
          role: string
          tenant_id: string
          token: string
          venue_ids: string[] | null
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          email: string
          expires_at: string
          id?: string
          invited_by?: string | null
          role: string
          tenant_id: string
          token: string
          venue_ids?: string[] | null
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          role?: string
          tenant_id?: string
          token?: string
          venue_ids?: string[] | null
        }
        Relationships: [
          {
            foreignKeyName: "invites_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      item_modifier_groups: {
        Row: {
          group_id: string
          item_id: string
          sort_order: number
          tenant_id: string
        }
        Insert: {
          group_id: string
          item_id: string
          sort_order?: number
          tenant_id: string
        }
        Update: {
          group_id?: string
          item_id?: string
          sort_order?: number
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "item_modifier_groups_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "modifier_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "item_modifier_groups_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "item_modifier_groups_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      item_variants: {
        Row: {
          id: string
          is_available: boolean
          item_id: string
          label: string
          label_zh: string | null
          price: number
          sort_order: number
          tenant_id: string
        }
        Insert: {
          id?: string
          is_available?: boolean
          item_id: string
          label: string
          label_zh?: string | null
          price: number
          sort_order?: number
          tenant_id: string
        }
        Update: {
          id?: string
          is_available?: boolean
          item_id?: string
          label?: string
          label_zh?: string | null
          price?: number
          sort_order?: number
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "item_variants_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "item_variants_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      items: {
        Row: {
          allergens: string[]
          base_price: number
          category_id: string
          compare_at_price: number | null
          created_at: string
          deleted_at: string | null
          description: string | null
          description_zh: string | null
          dietary_tags: string[]
          id: string
          image_blurhash: string | null
          image_url: string | null
          is_available: boolean
          is_featured: boolean
          name: string
          name_zh: string | null
          prep_time_minutes: number | null
          published_at: string | null
          restaurant_id: string
          slug: string
          sort_order: number
          spice_level: number
          status: string
          tenant_id: string
          updated_at: string
        }
        Insert: {
          allergens?: string[]
          base_price: number
          category_id: string
          compare_at_price?: number | null
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          description_zh?: string | null
          dietary_tags?: string[]
          id?: string
          image_blurhash?: string | null
          image_url?: string | null
          is_available?: boolean
          is_featured?: boolean
          name: string
          name_zh?: string | null
          prep_time_minutes?: number | null
          published_at?: string | null
          restaurant_id: string
          slug: string
          sort_order?: number
          spice_level?: number
          status?: string
          tenant_id: string
          updated_at?: string
        }
        Update: {
          allergens?: string[]
          base_price?: number
          category_id?: string
          compare_at_price?: number | null
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          description_zh?: string | null
          dietary_tags?: string[]
          id?: string
          image_blurhash?: string | null
          image_url?: string | null
          is_available?: boolean
          is_featured?: boolean
          name?: string
          name_zh?: string | null
          prep_time_minutes?: number | null
          published_at?: string | null
          restaurant_id?: string
          slug?: string
          sort_order?: number
          spice_level?: number
          status?: string
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "items_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "items_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "items_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      memberships: {
        Row: {
          accepted_at: string | null
          created_at: string
          invited_by: string | null
          role: string
          tenant_id: string
          updated_at: string
          user_id: string
          venue_ids: string[] | null
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          invited_by?: string | null
          role: string
          tenant_id: string
          updated_at?: string
          user_id: string
          venue_ids?: string[] | null
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          invited_by?: string | null
          role?: string
          tenant_id?: string
          updated_at?: string
          user_id?: string
          venue_ids?: string[] | null
        }
        Relationships: [
          {
            foreignKeyName: "memberships_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      menu_events: {
        Row: {
          created_at: string
          entity_id: string | null
          event: string
          id: number
          payload: Json | null
          restaurant_id: string | null
          session_id: string | null
          tenant_id: string | null
        }
        Insert: {
          created_at?: string
          entity_id?: string | null
          event: string
          id?: never
          payload?: Json | null
          restaurant_id?: string | null
          session_id?: string | null
          tenant_id?: string | null
        }
        Update: {
          created_at?: string
          entity_id?: string | null
          event?: string
          id?: never
          payload?: Json | null
          restaurant_id?: string | null
          session_id?: string | null
          tenant_id?: string | null
        }
        Relationships: []
      }
      menu_groups: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          menu_id: string
          name: string
          name_zh: string | null
          restaurant_id: string
          slug: string
          sort_order: number
          tenant_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          menu_id: string
          name: string
          name_zh?: string | null
          restaurant_id: string
          slug: string
          sort_order?: number
          tenant_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          menu_id?: string
          name?: string
          name_zh?: string | null
          restaurant_id?: string
          slug?: string
          sort_order?: number
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "menu_groups_menu_id_fkey"
            columns: ["menu_id"]
            isOneToOne: false
            referencedRelation: "menus"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "menu_groups_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "menu_groups_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      menu_schedules: {
        Row: {
          all_day: boolean
          ends_at: string | null
          id: string
          menu_id: string
          starts_at: string | null
          tenant_id: string
          weekday: number
        }
        Insert: {
          all_day?: boolean
          ends_at?: string | null
          id?: string
          menu_id: string
          starts_at?: string | null
          tenant_id: string
          weekday: number
        }
        Update: {
          all_day?: boolean
          ends_at?: string | null
          id?: string
          menu_id?: string
          starts_at?: string | null
          tenant_id?: string
          weekday?: number
        }
        Relationships: [
          {
            foreignKeyName: "menu_schedules_menu_id_fkey"
            columns: ["menu_id"]
            isOneToOne: false
            referencedRelation: "menus"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "menu_schedules_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      menus: {
        Row: {
          created_at: string
          deleted_at: string | null
          description: string | null
          hidden_when_unavailable: boolean
          id: string
          is_default: boolean
          name: string
          name_zh: string | null
          published_at: string | null
          restaurant_id: string
          slug: string
          sort_order: number
          status: string
          tenant_id: string
          theme_config: Json
          theme_config_draft: Json | null
          theme_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          hidden_when_unavailable?: boolean
          id?: string
          is_default?: boolean
          name: string
          name_zh?: string | null
          published_at?: string | null
          restaurant_id: string
          slug: string
          sort_order?: number
          status?: string
          tenant_id: string
          theme_config?: Json
          theme_config_draft?: Json | null
          theme_id?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          hidden_when_unavailable?: boolean
          id?: string
          is_default?: boolean
          name?: string
          name_zh?: string | null
          published_at?: string | null
          restaurant_id?: string
          slug?: string
          sort_order?: number
          status?: string
          tenant_id?: string
          theme_config?: Json
          theme_config_draft?: Json | null
          theme_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "menus_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "menus_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      modifier_groups: {
        Row: {
          created_at: string
          id: string
          is_required: boolean
          max_select: number
          min_select: number
          name: string
          name_zh: string | null
          restaurant_id: string
          tenant_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_required?: boolean
          max_select?: number
          min_select?: number
          name: string
          name_zh?: string | null
          restaurant_id: string
          tenant_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_required?: boolean
          max_select?: number
          min_select?: number
          name?: string
          name_zh?: string | null
          restaurant_id?: string
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "modifier_groups_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "modifier_groups_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      modifiers: {
        Row: {
          group_id: string
          id: string
          is_available: boolean
          name: string
          name_zh: string | null
          price_delta: number
          sort_order: number
          tenant_id: string
        }
        Insert: {
          group_id: string
          id?: string
          is_available?: boolean
          name: string
          name_zh?: string | null
          price_delta?: number
          sort_order?: number
          tenant_id: string
        }
        Update: {
          group_id?: string
          id?: string
          is_available?: boolean
          name?: string
          name_zh?: string | null
          price_delta?: number
          sort_order?: number
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "modifiers_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "modifier_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "modifiers_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      opening_hours: {
        Row: {
          closes: string | null
          id: string
          is_closed: boolean
          opens: string | null
          restaurant_id: string
          tenant_id: string
          weekday: number
        }
        Insert: {
          closes?: string | null
          id?: string
          is_closed?: boolean
          opens?: string | null
          restaurant_id: string
          tenant_id: string
          weekday: number
        }
        Update: {
          closes?: string | null
          id?: string
          is_closed?: boolean
          opens?: string | null
          restaurant_id?: string
          tenant_id?: string
          weekday?: number
        }
        Relationships: [
          {
            foreignKeyName: "opening_hours_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opening_hours_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          id: string
          item_id: string | null
          modifiers: Json
          name_snapshot: string
          notes: string | null
          order_id: string
          quantity: number
          tenant_id: string
          unit_price: number
          variant_id: string | null
        }
        Insert: {
          id?: string
          item_id?: string | null
          modifiers?: Json
          name_snapshot: string
          notes?: string | null
          order_id: string
          quantity?: number
          tenant_id: string
          unit_price: number
          variant_id?: string | null
        }
        Update: {
          id?: string
          item_id?: string | null
          modifiers?: Json
          name_snapshot?: string
          notes?: string | null
          order_id?: string
          quantity?: number
          tenant_id?: string
          unit_price?: number
          variant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_items_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "item_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          created_at: string
          daily_number: number
          guest_name: string | null
          guest_phone: string | null
          id: string
          notes: string | null
          restaurant_id: string
          room_number: string | null
          service_mode: string
          status: string
          subtotal: number
          table_number: string | null
          tenant_id: string
        }
        Insert: {
          created_at?: string
          daily_number: number
          guest_name?: string | null
          guest_phone?: string | null
          id?: string
          notes?: string | null
          restaurant_id: string
          room_number?: string | null
          service_mode: string
          status?: string
          subtotal?: number
          table_number?: string | null
          tenant_id: string
        }
        Update: {
          created_at?: string
          daily_number?: number
          guest_name?: string | null
          guest_phone?: string | null
          id?: string
          notes?: string | null
          restaurant_id?: string
          room_number?: string | null
          service_mode?: string
          status?: string
          subtotal?: number
          table_number?: string | null
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      qr_codes: {
        Row: {
          created_at: string
          id: string
          label: string | null
          menu_id: string | null
          restaurant_id: string
          style: Json
          table_number: string | null
          target_path: string
          tenant_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          label?: string | null
          menu_id?: string | null
          restaurant_id: string
          style?: Json
          table_number?: string | null
          target_path: string
          tenant_id: string
        }
        Update: {
          created_at?: string
          id?: string
          label?: string | null
          menu_id?: string | null
          restaurant_id?: string
          style?: Json
          table_number?: string | null
          target_path?: string
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "qr_codes_menu_id_fkey"
            columns: ["menu_id"]
            isOneToOne: false
            referencedRelation: "menus"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "qr_codes_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "qr_codes_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      qr_scans: {
        Row: {
          created_at: string
          id: number
          qr_code_id: string | null
          session_id: string | null
          tenant_id: string | null
        }
        Insert: {
          created_at?: string
          id?: never
          qr_code_id?: string | null
          session_id?: string | null
          tenant_id?: string | null
        }
        Update: {
          created_at?: string
          id?: never
          qr_code_id?: string | null
          session_id?: string | null
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "qr_scans_qr_code_id_fkey"
            columns: ["qr_code_id"]
            isOneToOne: false
            referencedRelation: "qr_codes"
            referencedColumns: ["id"]
          },
        ]
      }
      redirects: {
        Row: {
          created_at: string
          from_path: string
          id: string
          tenant_id: string | null
          to_path: string
        }
        Insert: {
          created_at?: string
          from_path: string
          id?: string
          tenant_id?: string | null
          to_path: string
        }
        Update: {
          created_at?: string
          from_path?: string
          id?: string
          tenant_id?: string | null
          to_path?: string
        }
        Relationships: [
          {
            foreignKeyName: "redirects_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      restaurants: {
        Row: {
          address: string | null
          cover_url: string | null
          created_at: string
          cuisine: string | null
          currency: string
          custom_domain: string | null
          description: string | null
          domain_verified_at: string | null
          hero_image_url: string | null
          id: string
          is_listed: boolean
          lat: number | null
          lng: number | null
          locale: string
          logo_url: string | null
          name: string
          name_zh: string | null
          ordering_enabled: boolean
          phone: string | null
          slug: string
          sold_out_reset_time: string
          status: string
          tenant_id: string
          theme: Json
          timezone: string
          updated_at: string
          whatsapp: string | null
        }
        Insert: {
          address?: string | null
          cover_url?: string | null
          created_at?: string
          cuisine?: string | null
          currency?: string
          custom_domain?: string | null
          description?: string | null
          domain_verified_at?: string | null
          hero_image_url?: string | null
          id?: string
          is_listed?: boolean
          lat?: number | null
          lng?: number | null
          locale?: string
          logo_url?: string | null
          name: string
          name_zh?: string | null
          ordering_enabled?: boolean
          phone?: string | null
          slug: string
          sold_out_reset_time?: string
          status?: string
          tenant_id: string
          theme?: Json
          timezone?: string
          updated_at?: string
          whatsapp?: string | null
        }
        Update: {
          address?: string | null
          cover_url?: string | null
          created_at?: string
          cuisine?: string | null
          currency?: string
          custom_domain?: string | null
          description?: string | null
          domain_verified_at?: string | null
          hero_image_url?: string | null
          id?: string
          is_listed?: boolean
          lat?: number | null
          lng?: number | null
          locale?: string
          logo_url?: string | null
          name?: string
          name_zh?: string | null
          ordering_enabled?: boolean
          phone?: string | null
          slug?: string
          sold_out_reset_time?: string
          status?: string
          tenant_id?: string
          theme?: Json
          timezone?: string
          updated_at?: string
          whatsapp?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "restaurants_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      staff: {
        Row: {
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          is_active: boolean
          restaurant_id: string | null
          role: string
          tenant_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          is_active?: boolean
          restaurant_id?: string | null
          role: string
          tenant_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          is_active?: boolean
          restaurant_id?: string | null
          role?: string
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "staff_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "staff_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          created_at: string
          current_period_end: string | null
          external_id: string | null
          id: string
          plan: string
          provider: string | null
          status: string
          tenant_id: string
        }
        Insert: {
          created_at?: string
          current_period_end?: string | null
          external_id?: string | null
          id?: string
          plan?: string
          provider?: string | null
          status?: string
          tenant_id: string
        }
        Update: {
          created_at?: string
          current_period_end?: string | null
          external_id?: string | null
          id?: string
          plan?: string
          provider?: string | null
          status?: string
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: true
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          billing_customer_id: string | null
          billing_provider: string | null
          created_at: string
          custom_domain: string | null
          id: string
          is_active: boolean
          name: string
          plan: string
          plan_status: string
          slug: string
          trial_ends_at: string | null
          updated_at: string
        }
        Insert: {
          billing_customer_id?: string | null
          billing_provider?: string | null
          created_at?: string
          custom_domain?: string | null
          id?: string
          is_active?: boolean
          name: string
          plan?: string
          plan_status?: string
          slug: string
          trial_ends_at?: string | null
          updated_at?: string
        }
        Update: {
          billing_customer_id?: string | null
          billing_provider?: string | null
          created_at?: string
          custom_domain?: string | null
          id?: string
          is_active?: boolean
          name?: string
          plan?: string
          plan_status?: string
          slug?: string
          trial_ends_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_invite: { Args: { p_token: string }; Returns: string }
      auth_can_manage: { Args: { tid: string }; Returns: boolean }
      auth_is_admin: { Args: { tid: string }; Returns: boolean }
      auth_role: { Args: never; Returns: string }
      auth_role_in: { Args: { tid: string }; Returns: string }
      auth_tenant_id: { Args: never; Returns: string }
      auth_tenant_ids: { Args: never; Returns: string[] }
      provision_tenant: { Args: { p_name?: string }; Returns: string }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
